import { Project } from "@/types";

export const projects: Project[] = [
  {
    id: 1,
    title: "Social Media Design",
    description:
      "A little corner where I turn things I love into visuals. Mostly fan edits, but also a playground for experimenting.",
    tech: ["Canva"],
    aspect: "4/5", // portrait — feed IG
    gallery: [
      { type: "image", src: "/image/9.png" },
      { type: "image", src: "/image/10.png" },
      { type: "image", src: "/image/11.png" },
      { type: "image", src: "/image/12.png" },
      { type: "image", src: "/image/13.png" },
      { type: "image", src: "/image/14.png" },
      { type: "image", src: "/image/15.png" },
      { type: "image", src: "/image/16.png" },
      { type: "image", src: "/image/Calum Hood.png" },
      { type: "image", src: "/image/CH bday design.png" },
      { type: "image", src: "/image/July 9, 2026 at 000 AM (1).png" },
      { type: "image", src: "/image/July 9, 2026 at 000 AM.png" },
    ],
  },
  {
    id: 2,
    title: "Video Editing",
    description:
      "Short-form video editing for vlog  and creative reels.",
    tech: ["Capcut", "InShot"],
    aspect: "16/9", // portrait — cocok untuk Reels
    gallery: [
      {
        type: "video",
        src: "/video/Calum Hood edits (1).mp4",
        poster: "/image/Screenshot 2026-09-24 223120.png",
      },
      {
        type: "video",
        src: "/video/0127 (online-video-cutter.com).mp4",
        poster: "/image/CH bday design (1).png",
      },
      {
        type: "video",
        src: "/video/CapCut _ Video Editor _ All-In-One Video Editing Software _ CapCut - Google Chrome 2026-07-05 00-29-05 (online-video-cutter.com) (3).mp4",
        poster: "/image/Screenshot 2026-09-24 231504.png",
      },
      {
        type: "video",
        src: "/video/recap p5(1).mp4",
        poster: "/image/Screenshot 2026-09-24 231530.png",
      },
      {
        type: "video",
        src: "/video/SaveClip.App_AQPtph8tmdWNvTTrkxE2lR17GotB3oN8GNYtKpyw4l3pxwxAYE_gl8X_F_wP0LzYy8OzFEGXMFEVjib8tpjMqrjvtJb0cxxlm9p4Jks.mp4",
        poster: "/image/Screenshot 2026-09-24 231547.png",
      },
    ],
  },
  {
    id: 3,
    title: "YouTube Thumbnails",
    description:
      "A collection of YouTube thumbnails created to make each video instantly eye-catching while keeping the visual style clean, bold, and easy to recognize.",
    tech: ["Canva"],
    aspect: "16/9", // ⭐ landscape — rasio thumbnail YouTube
    gallery: [
      { type: "image", src: "/image/pc.png" },
      { type: "image", src: "/image/podcast 1 ✅.png" },
      { type: "image", src: "/image/podcast 2.png" },
      { type: "image", src: "/image/podcast 3 ✅.png" },
      { type: "image", src: "/image/podcast 4.png" },
      { type: "image", src: "/image/podcast 5.png" },
      { type: "image", src: "/image/podcast 6 ✅.png" },
      { type: "image", src: "/image/podcast 7✅.png" },
      { type: "image", src: "/image/podcast 8.png" },
      { type: "image", src: "/image/podcast 9.png" },
      { type: "image", src: "/image/podcast 10.png" },
      { type: "image", src: "/image/podcast 11.png" },
      { type: "image", src: "/image/podcast 12.png" },
      { type: "image", src: "/image/podcast 13.png" },
      { type: "image", src: "/image/podcast 14.png" },
      { type: "image", src: "/image/podcast 15.png" },
      { type: "image", src: "/image/AsdCiPudZZs_maxres.jpg" },
      { type: "image", src: "/image/DqY8Jw-oorw_maxres.jpg" },
      { type: "image", src: "/image/EG2S34pmMxc_maxres.jpg" },
      { type: "image", src: "/image/LqMpc36ZIQs_maxres.jpg" },
      { type: "image", src: "/image/beethoven.png" },
      { type: "image", src: "/image/XyQoWV2w9Tc_maxres.jpg" },
      { type: "image", src: "/image/D4I5oyGnOpU_maxres.jpg" },
      { type: "image", src: "/image/NQwh7u891Dg_maxres.jpg" },
    ],
  },
  {
  id: 4,
  title: "Wallpapers Design",
  description:
    "Where my design journey began. What started as simple experiments making wallpapers for my own phone slowly became a way for me to explore my creativity. These pieces may have started as something just for fun, but they became the first step that made me fall in love with creating visuals.",
  tech: ["Canva", "Picsart", "Ibis Paint X"],
  aspect: "9/16",
  gallery: [
    { type: "image", src: "/image/WhatsApp Image 2026-09-25 at 12.07.54 AM.jpeg" },
    { type: "image", src: "/image/WhatsApp Image 2026-09-25 at 12.07.55 AM (1).jpeg" },
    { type: "image", src: "/image/WhatsApp Image 2026-09-25 at 12.07.55 AM.jpeg" },
    { type: "image", src: "/image/WhatsApp Image 2026-09-25 at 12.07.56 AM (1).jpeg" },
    { type: "image", src: "/image/WhatsApp Image 2026-09-25 at 12.07.56 AM.jpeg" },
    { type: "image", src: "/image/WhatsApp Image 2026-09-25 at 12.09.22 AM (1).jpeg" },
    { type: "image", src: "/image/WhatsApp Image 2026-09-25 at 12.09.22 AM.jpeg" },
    { type: "image", src: "/image/WhatsApp Image 2026-09-25 at 12.09.23 AM.jpeg" },
    { type: "image", src: "/image/Untitled7_20251006085122.jpg" },
    { type: "image", src: "/image/BITE THE APPLE (2).png" },
  ],
  },
  /*{
    id: 4,
    title: "On Camera Talent",
    description:
      "Featured in several production segments for YouTube News and creative content.",
    tech: ["On-Camera", "Script Reading", "Public Speaking"],
    aspect: "4/5",
    gallery: [
      { type: "image", src: "/image/12.png" },
      { type: "image", src: "/image/9.png" },
    ],
  },*/
  {
    id: 5,
    title: "Instagram Posts",
    description:
      "A few collection of Instagram post during my internship at Bingkai Karya, I created Instagram posts about music updates from both local and international artists. This project helped me strengthen my attention to detail",
    tech: ["Canva"],
    aspect: "4/5",
    gallery: [
      { type: "image", src: "/image/1 1.png" },
      { type: "image", src: "/image/2 2.png" },
      { type: "image", src: "/image/3 3.png" },
      { type: "image", src: "/image/4 4.png" },
      { type: "image", src: "/image/1.png" },
      { type: "image", src: "/image/2.png" },
      { type: "image", src: "/image/3.png" },
      { type: "image", src: "/image/4.png" },
      { type: "image", src: "/image/alternative 2 (7).png" },
      { type: "image", src: "/image/slide 2 (49).png" },
      { type: "image", src: "/image/slide 2 (50).png" },
      { type: "image", src: "/image/slide 2 (51).png" },
      { type: "image", src: "/image/alternative 2 (11).png" },
      { type: "image", src: "/image/slide 2 (70).png" },
      { type: "image", src: "/image/slide 2 (73).png" },
      { type: "image", src: "/image/slide 2 (72).png" },
      { type: "image", src: "/image/alternative 2 (12).png" },
      { type: "image", src: "/image/slide 2 (74).png" },
      { type: "image", src: "/image/slide 2 (75).png" },
      { type: "image", src: "/image/slide 2 (76).png" },
      { type: "image", src: "/image/122.png" },
      { type: "image", src: "/image/23.png" },
      { type: "image", src: "/image/34.png" },
      { type: "image", src: "/image/45.png" },
      { type: "image", src: "/video/1.png" },
      { type: "image", src: "/video/2.png" },
      { type: "image", src: "/video/3.png" },
      { type: "image", src: "/video/4.png" },
      { type: "image", src: "/image/111.png" },
      { type: "image", src: "/image/22.png" },
      {type: "image", src: "/image/33.png" },
      {type: "image", src: "/image/44.png" },
      {type: "image", src: "/image/1.1.png" },
      {type: "image", src: "/image/2.2.png" },
      {type: "image", src: "/image/3.3.png" },
      {type: "image", src: "/image/4.4.png" },
      {type: "image", src: "/image/1(1).png" },
      {type: "image", src: "/image/2(1).png" },
      {type: "image", src: "/image/3(1).png" },
      {type: "image", src: "/image/4(1).png" },
    ],
  },
  {
  id: 6,
  title: "Instagram Stories",
  description:
    "Created Instagram Stories as supporting content for Bingkai Karya’s music updates, featuring artist visuals with alternative headlines that remained connected to the main Instagram post. Each Story was designed to catch attention while directing audiences to the full article through a link.",
  tech: ["Canva"],
  aspect: "9/16",
  gallery: [
    { type: "image", src: "/image/Copy of Copy of Copy of STORY Bingkai Karya (2).jpg" },
    { type: "image", src: "/image/Copy of Copy of Copy of STORY Bingkai Karya (10).jpg" },
    { type: "image", src: "/image/Copy of Copy of Copy of STORY Bingkai Karya (20).jpg" },
    { type: "image", src: "/image/Copy of Copy of Copy of STORY Bingkai Karya (21).jpg" },
    { type: "image", src: "/image/Copy of Copy of Copy of STORY Bingkai Karya (22).jpg" },
    { type: "image", src: "/image/STORY Bingkai Karya (5).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (6).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (14).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (22).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (24).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (25).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (29).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (31).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (34).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (35).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (37).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (38).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (39).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (42).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (46).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (47).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (49).png" },
    { type: "image", src: "/image/STORY Bingkai Karya (53).png" },
    { type: "image", src: "/image/STORY Bingkai Karya.jpg" },
  ],
  },
];